### ISSUE TITLE
How to set the route?

### ISSUE THREAD

**Issue by dtrunk90** [limiter121/artillery-engine-tcp#1]
I'm running a microservice and can retrieve data with [rsc](https://github.com/making/rsc) without any problems:
```
$ rsc --stream --route find-all tcp://localhost:7000 | jq .
...
```

Now I don't know how to specify the route to call.
My test script:
```yml
config:
  target: "localhost"
  tcp:
    port: 7000
  phases:
    - duration: 30
      arrivalRate: 50
      name: "Short & light, Phase 0"
    - duration: 40
      arrivalRate: 50
      rampTo: 55
      name: "Ramping up, Phase 1"
    - duration: 45
      arrivalRate: 55
      name: "Max Load, Phase 2"

scenarios:
  - name: "Test: Scaling the load"
    engine: "tcp"
    flow:
      // what to do here to send requests without any data to the find-all route?
```
